### ISSUE TITLE
slow to load especially during scheduled hourly cron

### ISSUE THREAD

**Issue by sayanee** [webuildsg/webuild#251]
Tailing the log gives these details:

```sh
/Users/sayanee/.rvm/gems/ruby-2.3.0/gems/commander-4.2.1/lib/commander/user_interaction.rb:328: warning: constant ::TimeoutError is deprecated
/Users/sayanee/.rvm/gems/ruby-2.3.0/gems/net-ssh-2.9.2/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/sayanee/.rvm/gems/ruby-2.3.0/gems/net-ssh-2.9.2/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
...
Jul 11 00:06:27 <info> (/node_modules/webuild-events/events/index.js:98:14:) Success: Added 0 Meetup events
{ [Error: socket hang up]
  defaultMessage: 'Internal Server Error',
  message: 'socket hang up',
  code: '500' }
{ [Error: socket hang up]
  defaultMessage: 'Internal Server Error',
  message: 'socket hang up',
  code: '500' }
{ [Error: socket hang up]
  defaultMessage: 'Internal Server Error',
  message: 'socket hang up',
  code: '500' }
Jul 11 00:06:28 <info> (/node_modules/webuild-events/events/eventbriteEvents.js:132:12:filterEvents) Found 21 eventbrite.com tech events
```

**Comment by sayanee** [comment]
separate `config.js` into 2 parts: static and dynamic
